frwc64 = typeof frwc64 != 'undefined' ? frwc64 : {}
frwc64.wizards = typeof frwc64.wizards != 'undefined' ? frwc64.wizards : {}

frwc64.wizards.names = {
    splitter: function(input) {
      let prefixes = this.prefixes
      let suffixes = this.suffixes
      let modify = input
      let prefix = ''
      let name   = ''
      let suffix = ''

      for (var i = 0; i < prefixes.length; i++) {
        let pattern = new RegExp('^' + prefixes[i] + '')
        if (modify.match(pattern)) {
          prefix = prefixes[i]
          modify = modify.replace(prefixes[i], '')
          break
        }
      }
      for (var i = 0; i < suffixes.length; i++) {
        let pattern = new RegExp('' + suffixes[i] + '$')
        if (modify.match(pattern)) {
          suffix = suffixes[i]
          modify = modify.replace(suffixes[i], '')
          break
        }
      }
      name = modify.trim()
      return {prefix: prefix, name: name, suffix: suffix, fullname: input} 
    },
    prefixes: [
      '3D Wizz',
      'Adept',
      'Aeromancer',
      'Alchemist',
      'Alien Arcanist',
      'Arcanist',
      'Arch-Magician',
      'Arch-magician',
      'Archmagus',
      'Artificer',
      'Augurer',
      'Bard',
      'Battlemage',
      'Battle Mage',
      'Bringer',
      'Bunny Wizard',
      'Cartomancer',
      'Cat Wizard',
      'Chaos Mage',
      'Charmer',
      'Chronomancer',
      'Clairvoyant',
      'Cleric',
      'Colormancer',
      'Conjurer',
      'Crow Master',
      'Cryptomancer',
      'Cosmic Mage',
      'Diabolist',
      'Diviner',
      'Druid',
      'Edge Arcanist',
      'Electromancer',
      'Enchanter',
      'Evil Arcanist',
      'Evoker',
      'Fortune Master',
      'Fortune Teller',
      'Geomancer',
      'Ghost Eater',
      'Great Old One',
      'Hedge Wizard',
      'Hex Mage',
      'Holy Arcanist',
      'Holy Magus',
      'Holy Monk',
      'Hydromancer',
      'Ice Mage',
      'Illusionist',
      'Light Mage',
      'Loop Master',
      'Lunar Mage',
      'Magus',
      'Master Ape',
      'Master of Spots',
      'Medium',
      'Mystic',
      'Necromancer',
      'Null Mage',
      'Old',
      'Oracle',
      'Philosopher',
      'Prismatic Magi',
      'Punk Rock Arcanist',
      'Pyromancer',
      'Rogue Mage',
      'Runecaster',
      'Sage',
      'Scryer',
      'Shadow Mage',
      'Shaman',
      'Sky Master',
      'Solar Mage',
      'Sorcerer',
      'Sorceror',
      'Spellsinger',
      'Stellar Mage',
      'Summoner',
      'Supa Wizz',
      'Thaumaturge',
      'The Great and Magical',
      'The Wizard',
      'The Witch',
      'Transmuter',
      'Vampyre',
      'Void Disciple',
      'Voodoo Priest',
      'Wild Mage',
      'Wise',
      'Witch',
      'Wizard',
    ],
    suffixes: [
      'from the Abyss',
      'from the Shadow',
      'in the Shadows',
      'of Alfheim',
      'of Arcadia',
      'of Atlantis',
      'of Avalon',
      'of Cuckoo Land',
      'of Death',
      'of Dreams',
      'of El Dorado',
      'of Elysium',
      'of Limbo',
      'of Mu',
      'of Oz',
      'of Tartarus',
      'of the 7 Hues',
      'of the Arctic',
      'of the Ash',
      'of the Astral Plane',
      'of the Atheneum',
      'of the Bastion',
      'of the Belfry',
      'of the Berg',
      'of the Bibliotheca',
      'of the Boneyard',
      'of the Brambles',
      'of the Brine',
      'of the Canyon',
      'of the Capital',
      'of the Carnival',
      'of the Catacombs',
      'of the Circle',
      'of the Citadel',
      'of the Crag',
      'of the Crypt',
      'of the Cold',
      'of the Cosmos',
      'of the Court',
      'of the Desert',
      'of the Dunes',
      'of the End Times',
      'of the Ether',
      'of the Event Horizon',
      'of the Expanse',
      'of the Fey',
      'of the Field',
      'of the Forest',
      'of the Garden',
      'of the Glacier',
      'of the Gnostics',
      'of the Grave',
      'of the Great Blue',
      'of the Grotto',
      'of the Hall',
      'of the Havens',
      'of the Heath',
      'of the Heavens',
      'of The Hills',
      'of the Hills',
      'of the Hollow',
      'of the Hyperlight',
      'of the Ice',
      'of the Inferno',
      'of the Isle',
      'of the Keep',
      'of the Lake',
      'of the Light',
      'of the Loch',
      'of the Marsh',
      'of the Mist',
      'of the Morning Star',
      'of the Moors',
      'of the Mount',
      'of the Mountain',
      'of the North',
      'of the Oasis',
      'of the Obelisk',
      'of the Palms',
      'of the Pit',
      'of the Plains',
      'of the Platonic Shadow',
      'of the Psychic Leap',
      'of the Quantum Downs',
      'of the Quantum Shadow',
      'of the Rainbow',
      'of the Reach',
      'of the Realm',
      'of the River',
      'of the Riviera',
      'of the Road',
      'of the Rock',
      'of the Sacred Pillars',
      'of the Salt',
      'of the Sands',
      'of the Secret Fire',
      'of the Sea',
      'of the Shadow',
      'of the Steppe',
      'of the Sun',
      'of the Surf',
      'of the Swell',
      'of the Technochrome',
      'of the Temple',
      'of the Thorn',
      'of the Toadstools',
      'of the Tower',
      'of the Tundra',
      'of the Undead',
      'of the Valley',
      'of the Veil',
      'of the Villa',
      'of the Waste', 
      'of the West',
      'of the Wild',
      'of the Wold',
      'of the Wood',
      'of the Woodlands',
      'of Xanadu',
      'out of the Blizzard',
      'out of the Void',
      'The Great',
      'the Bearded',
    ],
}